### ISSUE TITLE
Update validateProps so that it outputs the component that the error came from

### ISSUE THREAD

**Issue by Quenty** [Roblox/roact#240] opened 2019-10-01 20:59 UTC
Update validateProps so that it outputs the component that the error came from. Right now it doesn't say where it's coming from, just the actual error text, which makes debugging difficult.

**Comment by Quenty** [comment] 2019-10-01 21:00
Potentially a duplicate of #237. However, this request is just asking for the element name, and not the stack element trace.

**Comment by LPGhatguy** [comment] 2019-10-01 21:05
I think we can close this as a duplicate of #237, since we probably want that stack trace too!

**Closed by LPGhatguy** 2019-10-01 21:05 UTC
